import cron from "node-cron";
import { logger } from "../utils/logger.js";
import mongoose from "mongoose";
import { errorResponse } from "../utils/helperfunctions.js";
import billGenerationDetails from "../models/billGenerationDetails.js";
import customerHouse from "../models/customerHouse.model.js";
import taxApplicable from "../models/taxApplicable.js";
import occupancyType from "../models/occupancyType.js";
import updateMaster from "../models/updateMaster.model.js";
import updateDetails from "../models/updateDetails.model.js";
